export const experiences = [
  {
    dateSpan: '2024 - Now',
    titles: ['Software Engineer'],
    company: 'Postilize',
    href: 'https://www.postilize.com/',
    description:
      'Building automation for law, accounting, and consulting firms at an early-stage startup.',
    skills: ['System Design', 'Software Testing'],
    technologies: ['JavaScript', 'React', 'Express', 'MongoDB'],
  },
  {
    dateSpan: '2023 - 2025',
    titles: ['Educator', 'Web Development Mentor'],
    company: 'Lighthouse Labs',
    href: 'https://www.lighthouselabs.ca/',
    description: 'Taught and mentored over 500 students in web development.',
    skills: ['Web Development', 'Content Delivery'],
    technologies: ['JavaScript', 'React', 'Express', 'SQL', 'Git'],
  },
  {
    dateSpan: '2023',
    titles: ['Developer', 'Undergraduate Program Secretary'],
    company: 'York University',
    href: 'https://www.yorku.ca/science/chemistry/',
    description: 'Built internal automation tools for the Department of Chemistry.',
    skills: ['Scripting', 'Task Automation'],
    technologies: ['JavaScript', 'Python', 'Selenium'],
  },
  {
    dateSpan: '2021 - 2023',
    titles: ['Co-founder'],
    company: 'Heritude Inc.',
    href: 'https://yfile.news.yorku.ca/2020/04/29/startup-focused-on-supporting-indigenous-artisans-wins-pitch-competition-coveted-spot-in-bestlab/',
    description: 'Co-founded a consumer products company. Reached break-even in fourteen months.',
    skills: ['Startup', 'Business Management'],
    technologies: ['Shopify', 'Amazon FBA'],
  },
  {
    dateSpan: '2019 - 2022',
    titles: ['Lead Site Coordinator', 'Operations Coordinator', 'Finance Coordinator'],
    company: "Let's Talk Science",
    href: 'https://letstalkscience.ca/',
    description: 'Led a team of three and tested a new volunteer portal ahead of launch.',
    skills: ['Leadership', 'Project Management', 'Documentation'],
    technologies: ['Google Suite', 'MailChimp'],
  },
];
